### ISSUE TITLE
Simplify valist.yml

### ISSUE THREAD

**Issue by awantoch** [valist-io/valist#178]
- Remove `type` and keep this internal
- Remove `build` and `install` fields
- Remove `out` and making `platforms` required with at least one entry
- Rename `org` to `name`, and use the resolver syntax to combine the repo name (i.e., valist/sdk)

Example `valist.yml`:

```yaml
name: valist/sdk
tag: 0.0.1
artifacts:
    linux/amd64: cmd/bin/main
```
