### ISSUE TITLE
[GoCLI] Valist YAML

### ISSUE THREAD

**Issue by awantoch** [valist-io/valist#98]
- Ability to consume `valist.yml`

Examples:

```
type: node
org: test
repo: node
tag: 0.0.1-rc.3
install: npm install
build: npm run build
```

```
type: go
org: test
repo: go
tag: 0.0.2
meta: README.md
build: make all
out: dist or dist/
```

```
type: go
org: test
repo: go
tag: 0.0.2
meta: README.md
build: make all
out: dist
artifacts:
    linux/amd64: bin/lin000x/hello-world
    darwin/amd64: bin/macz/hello-world
```
